### ISSUE TITLE
INSTALL_FAILED_NO_MATCHING_ABIS

### ISSUE THREAD

**Issue by dev-aritra** [chayxana/Restaurant-App#14]
Getting this error while trying to deploy the solution to a device.
Tested on both Android 6.0 and 7.0 devices.

Severity	Code	Description	Project	File	Line	Suppression State
Error		ADB0010: Failure [INSTALL_FAILED_NO_MATCHING_ABIS]
   at Mono.AndroidTools.Internal.AdbOutputParsing.CheckInstallSuccess(String output, String packageName) in E:\A\_work\157\s\External\androidtools\Mono.AndroidTools\Internal\AdbOutputParsing.cs:line 338
   at Mono.AndroidTools.AndroidDevice.<>c__DisplayClass94_0.<InstallPackage>b__0(Task`1 t) in E:\A\_work\157\s\External\androidtools\Mono.AndroidTools\AndroidDevice.cs:line 746
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()		 	0

**Comment by dev-aritra** [comment]
Solved

https://stackoverflow.com/questions/24572052/install-failed-no-matching-abis-when-install-apk/41969077#41969077
